<a href="https://colab.research.google.com/github/BottleSpink/Product-Review/blob/master/TFIDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import re
import numpy as np
from pprint import pprint
from sklearn.preprocessing import LabelEncoder



In [0]:
df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

#df_input.head()


In [5]:
df.shape, df_test.shape

((5959, 3), (2553, 2))

In [6]:


#df = df_input.drop_duplicates()
#df_test = df_input_test.drop_duplicates()
df.shape, df_test.shape


((5959, 3), (2553, 2))

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5959 entries, 0 to 5958
Data columns (total 3 columns):
Review Text     5959 non-null object
Review Title    5959 non-null object
topic           5959 non-null object
dtypes: object(3)
memory usage: 139.7+ KB


In [0]:
import string
from string import digits
from sklearn.feature_extraction.text import TfidfVectorizer

import re

def token(text):
    text = text.split(' ')
    table = str.maketrans('', '', string.punctuation)
    table1 = str.maketrans('','', digits)
    reg = re.compile('[^a-zA-Z ]')
    stripped = [w.translate(table) for w in text]
    stripped1 = [w.translate(table1) for w in stripped]
    stripped2 = [reg.sub('', w) for w in stripped1]
    stripped3 = [w for w in stripped2 if len(w)>1]
    return stripped3

In [0]:
vect_Title = TfidfVectorizer( max_features= 200, tokenizer=token , stop_words = 'english').fit(df["Review Title"].values.astype('U'))

vect_Title_Train = vect_Title.transform(df["Review Title"])
vect_Title_Test = vect_Title.transform(df_test["Review Title"])

vect_Title_Train=vect_Title_Train.toarray()
vect_Title_Test=vect_Title_Test.toarray()

words = vect_Title.get_feature_names()
words=["T_"+w for w in words]

keywords_Train=pd.DataFrame(vect_Title_Train, columns=words)
keywords_Test=pd.DataFrame(vect_Title_Test, columns=words)

keys_Train=[w for w in words if keywords_Train[w].sum()>60] 
#keys_Test=[w for w in words if keywords_Test[w].sum()] 

col_train=pd.concat([df, keywords_Train[keys_Train]],axis=1)
col_test=pd.concat([df_test, keywords_Test[keys_Train]],axis=1)


In [0]:
vect_Title = TfidfVectorizer( max_features= 200, tokenizer=token , stop_words = 'english').fit(df["Review Text"].values.astype('U'))

vect_Title_Train = vect_Title.transform(df["Review Text"])
vect_Title_Test = vect_Title.transform(df_test["Review Text"])

vect_Title_Train=vect_Title_Train.toarray()
vect_Title_Test=vect_Title_Test.toarray()

words = vect_Title.get_feature_names()
words=["R_"+w for w in words]

keywords_Train=pd.DataFrame(vect_Title_Train, columns=words)
keywords_Test=pd.DataFrame(vect_Title_Test, columns=words)

keys_Train=[w for w in words if keywords_Train[w].sum()>60] 
#keys_Test=[w for w in words if keywords_Test[w].sum()] 

col_train=pd.concat([col_train, keywords_Train[keys_Train]],axis=1)
col_test=pd.concat([col_test, keywords_Test[keys_Train]],axis=1)


In [9]:
keys_Train

['R_arrived',
 'R_away',
 'R_awful',
 'R_bad',
 'R_better',
 'R_big',
 'R_bottle',
 'R_bottles',
 'R_bought',
 'R_box',
 'R_br',
 'R_brand',
 'R_broken',
 'R_buy',
 'R_buying',
 'R_came',
 'R_chocolate',
 'R_day',
 'R_delivered',
 'R_did',
 'R_didnt',
 'R_different',
 'R_disappointed',
 'R_does',
 'R_doesnt',
 'R_dont',
 'R_energy',
 'R_feel',
 'R_fish',
 'R_flavor',
 'R_gave',
 'R_going',
 'R_good',
 'R_got',
 'R_great',
 'R_gross',
 'R_gummies',
 'R_gummy',
 'R_hard',
 'R_help',
 'R_horrible',
 'R_huge',
 'R_im',
 'R_ingredients',
 'R_item',
 'R_ive',
 'R_just',
 'R_know',
 'R_like',
 'R_little',
 'R_lot',
 'R_love',
 'R_make',
 'R_money',
 'R_oil',
 'R_opened',
 'R_order',
 'R_ordered',
 'R_package',
 'R_pills',
 'R_powder',
 'R_price',
 'R_product',
 'R_products',
 'R_protein',
 'R_quality',
 'R_really',
 'R_received',
 'R_return',
 'R_sent',
 'R_skin',
 'R_smell',
 'R_stomach',
 'R_stuck',
 'R_sugar',
 'R_sure',
 'R_swallow',
 'R_sweet',
 'R_taking',
 'R_taste',
 'R_tasted',
 'R_t

In [74]:
col_test.head()

Review Text  ... R_work
0  I use chia seed in my protein shakes. These ta...  ...    0.0
1  I use chia seed in my protein shakes. These ta...  ...    0.0
2                            Don’t waste your money.  ...    0.0
3  I use the book 'Fortify Your Life' by Tieraona...  ...    0.0
4  I use the book 'Fortify Your Life' by Tieraona...  ...    0.0

[5 rows x 129 columns]

In [11]:
col_train.shape, col_test.shape
#col_train.to_csv('train_chk.csv')

((5959, 131), (2553, 130))

In [12]:
df['topic'].unique()

array(['Shipment and delivery', 'Not Effective', 'Customer Service',
       'Allergic', 'Texture', 'Quality/Contaminated', 'Color and texture',
       'Bad Taste/Flavor', 'Too big to swallow', 'Smells Bad',
       'Too Sweet', 'Ingredients', 'Expiry', 'Packaging',
       'Wrong Product received', 'Pricing', 'False Advertisement',
       'Inferior to competitors', "Didn't Like", 'Customer Issues',
       'Hard to Chew'], dtype=object)

In [13]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(col_train['topic'].astype(str))
y = integer_encoded.ravel()
np.unique(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [0]:
x = col_train.drop('topic', axis = 1)
x = x.drop('Review Text', axis = 1)
x = x.drop('Review Title', axis = 1)


In [15]:
x.head()

T_arrived  T_awful  T_bad  T_broken  ...  R_way  R_weird  R_wont  R_work
0        0.0      0.0    0.0       0.0  ...    0.0      0.0     0.0     0.0
1        0.0      0.0    0.0       0.0  ...    0.0      0.0     0.0     0.0
2        0.0      0.0    0.0       0.0  ...    0.0      0.0     0.0     0.0
3        0.0      0.0    0.0       0.0  ...    0.0      0.0     0.0     0.0
4        0.0      0.0    0.0       0.0  ...    0.0      0.0     0.0     0.0

[5 rows x 128 columns]

In [16]:
from sklearn.model_selection import train_test_split
x_train_b, x_test_b, y_train_b, y_test_b = train_test_split(x, y, test_size = 0.33)

x_train_b

T_arrived   T_awful     T_bad  ...   R_weird    R_wont    R_work
2286        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3393        0.0  0.000000  1.000000  ...  0.000000  0.000000  0.000000
4421        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5314        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2404        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
31          0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
522         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2683        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
312         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2144        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3478        0.0  0.000000  0.733671  ...  0.000000  0.000000  0.000000
2213        0.0  0.000000  0.000000  ...  0.000000  0.648231  0.000000
1958        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1263        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4095        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5667        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
486         0.0  0.723697  0.000000  ...  0.000000  0.000000  0.000000
3193        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
616         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.287387
697         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1738        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3755        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1250        0.0  1.000000  0.000000  ...  0.000000  0.000000  0.000000
2464        0.0  0.000000  0.000000  ...  0.000000  0.285224  0.000000
5645        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1098        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5027        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1800        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.325665
3734        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2705        0.0  0.000000  0.733671  ...  0.000000  0.000000  0.000000
...         ...       ...       ...  ...       ...       ...       ...
746         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4933        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
166         0.0  0.000000  0.000000  ...  0.000000  0.064731  0.000000
2715        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
946         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.175865
414         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2852        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2514        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4140        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1778        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2595        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5412        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2314        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5117        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
756         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
613         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1477        0.0  0.000000  0.000000  ...  0.263947  0.000000  0.000000
1581        0.0  0.000000  1.000000  ...  0.000000  0.000000  0.000000
3140        0.0  0.000000  0.000000  ...  0.000000  0.387564  0.000000
999         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1628        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
748         0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5909        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3231        0.0  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3458        0.0  0.000000  0.0

In [0]:
from xgboost import XGBClassifier
# fit model no training data
model = XGBClassifier(objective ='multi:softprob', learning_rate = 0.8, max_depth = 5)
xgb_mod = model.fit(x_train_b, y_train_b)
pred_xgb = xgb_mod.predict(x_test_b)

In [18]:
pred_xgb = xgb_mod.predict(x_test_b)
#pred_rf = rf.predict(x_test_b)
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
xg = f1_score ( y_test_b, pred_xgb, average = 'weighted')
xg_a = accuracy_score ( y_test_b, pred_xgb)
xg_a, xg

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(0.3335027961362481, 0.3283528387265982)

In [19]:
x_test_b

T_arrived   T_awful     T_bad  ...   R_weird    R_wont    R_work
2564   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4816   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5033   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3746   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5188   0.447554  0.000000  0.000000  ...  0.000000  0.000000  0.000000
207    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2146   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
142    0.000000  0.000000  0.579682  ...  0.000000  0.000000  0.000000
4256   0.000000  0.000000  0.000000  ...  0.682171  0.000000  0.000000
5132   0.000000  0.000000  1.000000  ...  0.000000  0.000000  0.000000
132    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
453    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2920   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1689   0.503617  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3910   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
178    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2243   0.000000  0.723697  0.000000  ...  0.000000  0.000000  0.000000
218    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.169790
4665   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
279    0.000000  0.000000  0.000000  ...  0.438862  0.000000  0.000000
3685   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
693    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5278   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4838   0.000000  0.000000  0.487543  ...  0.000000  0.000000  0.000000
1570   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2963   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.431289
357    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5379   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1189   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.193406
5813   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
...         ...       ...       ...  ...       ...       ...       ...
704    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
410    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4422   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2529   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2008   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
418    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
763    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3306   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
5625   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3429   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1182   0.000000  0.000000  0.000000  ...  0.408138  0.000000  0.000000
1980   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.329761
351    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2422   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1909   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
202    0.000000  0.000000  0.000000  ...  0.205461  0.000000  0.000000
5505   0.454402  0.000000  0.000000  ...  0.000000  0.000000  0.000000
929    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.729093
4029   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
4978   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.479395
5222   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
628    0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2345   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3706   0.000000  0.000000  0.000000  ...  0.000000  0.256059  0.000000
1967   0.000000  0.000000  0.0

In [20]:
np.unique(y_train_b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
probs = xgb_mod.predict_proba(x_test_b)
ind = x_test_b.index
#labels = np.unique(df['topic'])
df_cm = pd.DataFrame(probs, ind)
df_cm.head()

0         1         2   ...        18        19        20
2564  0.007629  0.475200  0.011927  ...  0.000065  0.000380  0.000012
4816  0.001565  0.556443  0.000198  ...  0.000042  0.000190  0.000039
5033  0.011472  0.010668  0.001747  ...  0.000063  0.000723  0.000405
3746  0.003428  0.000247  0.000103  ...  0.000014  0.000047  0.000079
5188  0.046052  0.016482  0.009749  ...  0.000038  0.000578  0.000071

[5 rows x 21 columns]

In [22]:
df.iloc[1297]

Review Text     Awful! Do not buy this! Just got this package ...
Review Title                                       Waste of money
topic                                            Customer Service
Name: 1297, dtype: object

In [23]:
pred_xgb

array([ 1,  1, 12, ...,  1, 12,  2])

In [26]:
best_n = np.argsort(probs, axis=1)[:,-6:]
#best_n = np.argsort(probs, axis=1)[::-1][:6]
best_n[0], probs[0]

(array([16,  0,  2, 14,  4,  1]),
 array([7.6292856e-03, 4.7519976e-01, 1.1926617e-02, 3.0422216e-06,
        4.6404302e-01, 7.2495932e-05, 1.2296824e-03, 3.1648029e-05,
        2.4376543e-06, 5.1342540e-05, 1.1988062e-03, 2.1139966e-04,
        4.4552120e-04, 1.4563135e-04, 3.3266138e-02, 2.4190409e-05,
        3.0634857e-03, 9.9854078e-04, 6.4877313e-05, 3.7995659e-04,
        1.2079475e-05], dtype=float32))

In [25]:
np.mean(np.array([1 if y_test_b[k] in best_n[k] else 0 for k in range(len(best_n))]))

1.0

In [0]:
col_test = col_test.drop('Review Text', axis = 1)
col_test = col_test.drop('Review Title', axis = 1)

In [0]:
#from xgboost import XGBClassifier
# fit model no training data
#model = XGBClassifier(objective ='multi:softprob', learning_rate = 0.8, max_depth = 5)
xgb_mod_t = model.fit(x, y)
pred_xgb_t = xgb_mod_t.predict(col_test)

In [29]:
#pred_xgb_t = xgb_mod.predict(col_test)
probs_t = xgb_mod.predict_proba(col_test)
probs_t

array([[3.7970517e-03, 4.8785347e-01, 1.2706043e-03, ..., 6.9610763e-04,
        6.2204979e-04, 4.3552162e-04],
       [3.7970517e-03, 4.8785347e-01, 1.2706043e-03, ..., 6.9610763e-04,
        6.2204979e-04, 4.3552162e-04],
       [2.0640822e-02, 2.2993227e-02, 7.8465808e-03, ..., 1.4876986e-04,
        1.4292122e-01, 6.3076528e-04],
       ...,
       [8.5511550e-02, 8.7438697e-01, 4.9546434e-05, ..., 1.6822923e-05,
        3.9136771e-02, 3.4643388e-05],
       [5.8522047e-03, 2.7237287e-02, 1.2413155e-03, ..., 7.1495604e-05,
        5.8726109e-05, 4.2142605e-05],
       [8.6148858e-02, 1.7568758e-01, 1.3159249e-03, ..., 3.3276979e-04,
        5.6945566e-02, 1.8477059e-04]], dtype=float32)

In [30]:
pred_xgb_t

array([ 1,  1, 11, ...,  1, 14,  4])

In [31]:
best_t = np.argsort(probs_t, axis=1)[:,-6:]
best_t

array([[10,  6, 17, 16, 14,  1],
       [10,  6, 17, 16, 14,  1],
       [ 1, 10, 13, 14, 19, 11],
       ...,
       [17, 11, 14, 19,  0,  1],
       [ 6, 17,  0,  9,  1, 14],
       [11, 10, 19,  0,  1,  4]])

In [32]:
df_test.head()

Review Text                              Review Title
0  I use chia seed in my protein shakes. These ta...                                  Bad tast
1  I use chia seed in my protein shakes. These ta...                                  Bad tast
2                            Don’t waste your money.                    No change. No results.
3  I use the book 'Fortify Your Life' by Tieraona...  Good Vegan Choice, Poor Non Vegan Choice
4  I use the book 'Fortify Your Life' by Tieraona...  Good Vegan Choice, Poor Non Vegan Choice

In [0]:
#df_test['cnt'] = df_test.groupby('Review Text')['Review Text'].transform('count')
df_test['new'] = 1


In [0]:
df_test['wins'] = df_test.groupby('Review Text').cumcount()+1
#df_test['wins'] = df_test['wins']-1

In [52]:
df_test.head()

Review Text  ... wins
0  I use chia seed in my protein shakes. These ta...  ...    1
1  I use chia seed in my protein shakes. These ta...  ...    2
2                            Don’t waste your money.  ...    1
3  I use the book 'Fortify Your Life' by Tieraona...  ...    1
4  I use the book 'Fortify Your Life' by Tieraona...  ...    2

[5 rows x 4 columns]

In [53]:
df_test.shape

(2553, 4)

In [54]:
best_t[9]

array([ 0, 11, 17,  6, 12, 15])

In [55]:
best = pd.DataFrame(best_t)
df_m = pd.concat([df_test, best], axis =1)
df_m.columns = ['Review Text','Review Title', 'new', 'wins', 'F', 'E', 'D', 'C', 'B', 'A']
df_m.head()

Review Text  ...   A
0  I use chia seed in my protein shakes. These ta...  ...   1
1  I use chia seed in my protein shakes. These ta...  ...   1
2                            Don’t waste your money.  ...  11
3  I use the book 'Fortify Your Life' by Tieraona...  ...  14
4  I use the book 'Fortify Your Life' by Tieraona...  ...  14

[5 rows x 10 columns]

In [0]:
def fun(win, A, B, C, D, E, F): 
  
    if win == 1:
        return A
  
    elif win == 2: 
        return B
    
    elif win == 3: 
        return C
      
    elif win == 4: 
        return D
      
    elif win == 5: 
        return E
  
    else: 
        return F
        

In [0]:
df_m['try'] = df_m.apply(lambda x: fun(x['wins'], x['A'], x['B'], x['C'], x['D'], x['E'], x['F']), axis = 1)


In [0]:
df_s = df_m.drop([ 'new', 'wins', 'A', 'B', 'C', 'D', 'E', 'F'], axis  =1)

In [0]:
df_s['topic'] = label_encoder.inverse_transform(df_s['try'])
df_s = df_s.drop('try', axis = 1)

In [60]:
df_s.head()

Review Text  ...                 topic
0  I use chia seed in my protein shakes. These ta...  ...      Bad Taste/Flavor
1  I use chia seed in my protein shakes. These ta...  ...  Quality/Contaminated
2                            Don’t waste your money.  ...         Not Effective
3  I use the book 'Fortify Your Life' by Tieraona...  ...  Quality/Contaminated
4  I use the book 'Fortify Your Life' by Tieraona...  ...              Allergic

[5 rows x 3 columns]

In [0]:
df_s.to_csv('sample_8.csv', index = False)

In [62]:
df_s.topic.unique()

array(['Bad Taste/Flavor', 'Quality/Contaminated', 'Not Effective',
       'Allergic', 'Smells Bad', 'Texture', 'Shipment and delivery',
       'Wrong Product received', 'Expiry', 'Packaging',
       'Inferior to competitors', 'Color and texture',
       'Too big to swallow', 'Customer Service', 'Customer Issues',
       'Pricing', 'Too Sweet', 'Ingredients', "Didn't Like",
       'False Advertisement', 'Hard to Chew'], dtype=object)